version: "3.8"

services:
  node:
    container_name: tm1-oauth
    image: node:16
    build:
      context: .
    ports:
      - "$PORT:$TARGET_PORT"
    depends_on:
      - db
  db:
    container_name: db
    image: "postgres:12"
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - pgdata1:/var/lib/postgresql/data

volumes:
  pgdata1: {}
